# Generated by Django 2.1.4 on 2019-02-03 07:58

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('dob', models.DateField()),
                ('live_in', models.BooleanField()),
                ('address', models.CharField(max_length=200)),
                ('notes', models.TextField(max_length=5000)),
                ('custody', models.BooleanField()),
                ('adopted', models.BooleanField()),
                ('legitimate', models.BooleanField()),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('occupation', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('home_telephone', models.CharField(max_length=30)),
                ('work_telephone', models.CharField(max_length=100)),
                ('domicile', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('name_at_birth', models.CharField(max_length=255)),
                ('marital_status', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ClientSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='client.Client')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Spouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('domicile', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('dom', models.DateField()),
                ('place_of_marriage', models.CharField(max_length=100)),
                ('marriage_contract_exists', models.BooleanField()),
                ('marriage_contract', models.FileField(upload_to='media/')),
                ('seperated', models.BooleanField()),
                ('divorced', models.BooleanField()),
                ('dos', models.DateField()),
                ('dod', models.DateField()),
                ('divorce_contract', models.FileField(upload_to='media/')),
                ('partnerSession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.ClientSession')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='child',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientsessions', to='client.ClientSession'),
        ),
    ]
