# Generated by Django 2.1.4 on 2019-02-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20190202_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='notes',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='work_telephone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='divorce_contract',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='dod',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='dos',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='marriage_contract',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
