# Generated by Django 2.1.5 on 2019-02-05 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0003_auto_20190203_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ClientLoginProfile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientsession',
            name='lawyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lawyer', to='client.Client'),
        ),
        migrations.AlterField(
            model_name='clientsession',
            name='client',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='client.Client'),
        ),
    ]
