# Generated by Django 2.1.5 on 2019-02-05 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20190205_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsession',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='client.Client'),
        ),
        migrations.AlterField(
            model_name='clientsession',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer', to='client.Client'),
        ),
    ]
