# Generated by Django 2.1.5 on 2019-02-13 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20190212_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsession',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer', to='lawOffice.Lawyer'),
        ),
    ]
