# Generated by Django 2.1.5 on 2019-02-14 00:01

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20190213_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='clientsession',
            name='assign_executor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='marital_status',
            field=models.CharField(choices=[('MR', 'Married'), ('SL', 'Single'), ('LT', 'Living together')], default='SL', max_length=2),
        ),
    ]
