# Generated by Django 2.1.5 on 2019-02-14 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_auto_20190214_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executor',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.ClientSession'),
        ),
    ]
